version: '3.3'
services:
  db-backend:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  vhost:
