spring:
  profiles:
    active: "local"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Naming strategy
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: true

    # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
    # stripped before adding them to the entity manager)

    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    show-sql: true

---

# Local
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/paiduaygun?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    #    # Show or not log for each sql query
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: local

---

# Dev
spring:
  datasource:
    url: jdbc:mysql://206.189.94.28:3306/lrckreport?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    #    # Show or not log for each sql query
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: dev

server:
  error:
    include-stacktrace: on_trace_param